# Generated by Django 2.2.2 on 2019-06-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивировано')),
            ],
        ),
    ]
